# Runs the command and prints a notification
def execute(cmd)
  if system(cmd)
    n 'Build succeeded', 'pandoc', :success
  else
    n 'Build failed', 'pandoc', :failed
  end
end

def build_slides
  execute %{
  pandoc -t html5 --mathjax -V theme="beige" --template "./reveal.js/template-revealjs.html" -t revealjs --standalone --section-divs -V transition="concave" --no-highlight -V highlight-style="solarized_dark" websharper.md -o "websharper.html"
  } 
end

guard :shell do
  watch(%r{.*\.md$})          { build_slides }
end